### ISSUE TITLE
Mobile: Can not add members to channel

### ISSUE THREAD

**Issue by Dr-Blank** [The-Commit-Company/raven#1339]
![Image](https://github.com/user-attachments/assets/b4b83da5-531a-44b8-91f3-71bd614bab80)

This error happens when adding members and also when trying to add channel on home. My guess is any button that has a popup causes this issue.

ERPNext: v15.51.2 (version-15)

Frappe Framework: v15.56.0 (version-15)

Raven: v2.0.3 (develop)

**Comment by nikkothari22** [comment]
Hey @Dr-Blank 

This was fixed in the recent release. Can you pull the latest update and run bench build? 

If you're on Frappe Cloud, this should be fixed with a deployment.

**Comment by Dr-Blank** [comment]
@nikkothari22 I did do `git pull` in raven and `bench build` just before creating the issue however, this error still pops up on mobile.

my head is on commit `8cfa448b77c232388d15fe4d4fa261cb3740c771` which is the latest on develop branch (https://github.com/The-Commit-Company/raven/commit/8cfa448b77c232388d15fe4d4fa261cb3740c771)

**Comment by nikkothari22** [comment]
@Dr-Blank Since dependencies were updated, maybe try running `bench update --requirements --build`?

**Comment by nikkothari22** [comment]
@Dr-Blank I am closing this for now. Feel free to open it if the issue isn't fixed after applying the suggestions above.
